export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";

export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
//load user
export const USER_LOADED = "USER_LOADED";
export const ADMIN_LOADED = "ADMIN_LOADED";
export const ADMIN_LOADED_ERROR = "ADMIN_LOADED_ERROR";
export const AUTH_ERROR = "AUTH_ERROR";
export const USER_LOADED_ERROR = "USER_LOADED_ERROR";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const LOGOUT = "LOGOUT";

//PRODUCTs
export const GET_PRODUCT = "GET_PRODUCT";
export const GET_PRODUCTS = "GET_PRODUCTS";
export const PRODUCT_ERROR = "PRODUCT_ERROR";
export const CLEAR_PRODUCT = "CLEAR_PRODUCT";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const ACCOUNT_DELETED = "ACCOUNT_DELETED";
export const PRODUCT_DETAILS_FAIL = "PRODUCT_DETAILS_FAIL";
export const PRODUCT_DETAILS_REQUEST = "PRODUCT_DETAILS_REQUEST";
export const PRODUCT_DETAILS_SUCCESS = "PRODUCT_DETAILS_SUCCESS";
export const GET_PRODUCT_BY_CATEGORY = "GET_PRODUCT_BY_CATEGORY";

//Categories
export const GET_CATEGORY = "GET_CATEGORY";
export const CATEGORY_ERROR = "CATEGORY_ERROR";
export const UPDATE_CATEGORY = "UPDATE_CATEGORY";
export const CLEAR_CATEGORY = "CLEAR_CATEGORY";
export const GET_CATEGORIES = "GET_CATEGORIES";
export const CATEGORIES_DETAILS_FAIL = "CATEGORIES_DETAILS_FAIL";
export const CATEGORIES_DETAILS_SUCCESS = "CATEGORIES_DETAILS_SUCCESS";

//cart
export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const UPDATE_CART_ITEM_QUANTITY = "UPDATE_CART_ITEM_QUANTITY";
export const CLEAR_CART = "CLEAR_CART";

//order
export const GET_ORDERS = "GET_ORDERS";
export const ORDERS_ERROR = "ORDERS_ERROR";